controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_sortie_inscrit:
    path: /sortie/inscrit/{id}
    controller: App\Controller\SortieController::inscrit

app_sortie_desist:
    path: /sortie/desist/{id}
    controller: App\Controller\SortieController::desist